name: Build and Publish

on:
  push:
    branches: ["master"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image name
        id: image
        run: |
          LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "value=$LOWERCASE_REPO" >> "$GITHUB_OUTPUT"

      - name: Extract version from Cargo.toml
        id: cargo-version
        run: |
          version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.image.outputs.value }}:latest
            ${{ env.REGISTRY }}/${{ steps.image.outputs.value }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ steps.image.outputs.value }}:${{ steps.cargo-version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
